spring:
  application:
    name: photography-booking-api

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL}
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            jdbc:
              lob:
                non_contextual_creation: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: simple

server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: /

logging:
  level:
    com.photography.booking: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Custom application properties
app:
  cors:
    allowed-origins: ${FRONTEND_URL},${FRONTEND_URL_PROD}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours

  admin:
    default:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
      phone: ${ADMIN_PHONE}
      email: ${ADMIN_EMAIL}
      fullName: ${ADMIN_FULL_NAME}

  email:
    from: ${MAIL_USERNAME}
    admin: ${ADMIN_EMAIL}
    enabled: ${EMAIL_ENABLED}

# MNotify SMS Configuration
mnotify:
  api:
    key: ${MNOTIFY_API_KEY}
    url: ${MNOTIFY_API_URL}
  sender:
    id: ${MNOTIFY_SENDER_ID}
  enabled: ${SMS_ENABLED}
