spring:
  application:
    name: photography-booking-api

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: simple

server:
  port: 8000

logging:
  level:
    com.juls.sowlstudios: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom application properties
app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001

  jwt:
    secret: test-photography-booking-secret-key-that-should-be-at-least-256-bits-long-for-testing
    expiration: 86400000 # 24 hours

  admin:
    default:
      username: admin
      password: admin123
      email: admin@photography.com
      fullName: System Administrator

  email:
    from: test@gmail.com
    admin: admin@photography.com
    enabled: false

# MNotify SMS Configuration
mnotify:
  api:
    key: test-api-key
    url: https://api.mnotify.com/api/sms/quick
  sender:
    id: test-sender-id
  enabled: false
